### PR TITLE
Enumerable methods

### PR DESCRIPTION
**Pull request by 1v4n4**
We created our versions of Ruby methods  #each, #my_each_with_index , #my_select, #my_all? , #my_any?, #my_none?, #my_count, #my_map, modified to take procs and blocks too, and #my_inject.

### CODE REVIEW

**Review by Berabjesus — CHANGES_REQUESTED** [review]
## Status: CHANGES REQUIRED :warning: :construction: 
#### Hi @1v4n4 and @TedLivist a very good start :+1. Good read me instruction on how to clone the repo.

### However, out of 79 tests 42 are failing so you do have a few changes to carry out before we proceed so please take a look at the things you have to work on and their respective review comments below. Check if your enum methods satisfy the following requirements.

### my_each
- [x] my_each returns an Enumerator if no block is given

### my_each_with_index
- [x] my_each_with_index returns an enumerator if no block is given
- [x] when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
- [x]  when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [x] when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

### my_select
- [x] returns an enumerator if no block is given

### my_all?
- [x] when no block or argument is given returns true when none of the collection members are false or nil
- [x] when no block or argument is given returns false when one of the collection members are false or nil
- [x] when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [x] when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns false if any of the collection is not a member of such class
- [x] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [x] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [x] when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

### my_any?
- [x] when no block or argument is given returns true if at least one of the collection is not false or nil
- [x] when no block or argument is given returns false if at least one of the collection is not true
- [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [x] when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [x] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [x] when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

### my_none?
- [x] when no block or argument is given returns true only if none of the collection members is true
- [x] when no block or argument is given returns false only if one of the collection members is true
- [x] when a class is passed as an argument returns true if none of the collection is a member of such class
- [x] when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns false if any of the collection is a member of such class
- [x] when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [x] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [x] when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

### my_count
- [x] returns the number of items in enum through enumeration
- [x] returns the number of items in enum through enumeration::range
- [x] counts the number of items in enum that are equal to item if an argument is given

### my_map
- [x] returns an Enumerator if no block is given

### my_inject
- [x] searches for the longest word in an array of strings
- [x] when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
- [x] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [x] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [x] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [x] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range

##**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# Status: Changes Required :tada: 

Hey @1v4n4 and @TedLivist, Welldone for the job done , however out of 79 test cases 10 failed, for us to approve this project, all cases must passed. Here are few changes to make 
Failed examples:

# my_each_with_index
 
- [x] my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
- [x] my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [x]  my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [x] my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

 # my_all? 

- [x]   my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

# my_any?

- [x]   my_any? when no block or argument is given returns false if at least one of the collection is not true
- [x]  my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [x]  my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex.

# my_none?
 
- [x]  my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [x]  my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern


Kindly implement those changes and request for another review

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @1v4n4 and @TedLivist
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Well done for the job done, however out of 79 test cases 5 failed, for us to approve this project, all cases must be passed. Here are few changes to make  👇.
## my_each_with_index
- [ ] #my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
## my_all
- [ ] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
## my_any
- [ ] #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [ ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
## my_none
- [ ] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the patter

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# Status: Changes Required :tada: 

Hey @1v4n4 and @TedLivist. Welldone for the changes, Your code still failing, here are the failing examples 
Failed examples:

# my_all?
 

- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex

# my_any?

- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [ ] my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex

 # my_none?

- [ ]  my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex

Please submit for another review when fixed.

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 

## Hello, @1v4n4. You have done a great job. The methods pass all the test cases. Good work implementing the changes that the previous Code Reviewer suggested. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next project.

**Pull request merged**
